package capture

import (
	"testing"
)

const testData = `# Generated by iptables-save v1.8.7 on Thu Jul 30 12:00:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j DROP
-A INPUT -s 10.0.0.0/8 -j DROP
-A INPUT -j DROP
COMMIT
# Completed on Thu Jul 30 12:00:00 2026`

func TestParse(t *testing.T) {
	state, err := parse(testData)
	if err != nil {
		t.Fatalf("parse failed: %v", err)
	}

	if len(state.Tables) != 1 {
		t.Fatalf("expected 1 table, got %d", len(state.Tables))
	}

	filter := state.Tables[0]
	if filter.Name != "filter" {
		t.Errorf("expected table name 'filter', got '%s'", filter.Name)
	}

	if len(filter.Chains) != 3 {
		t.Fatalf("expected 3 chains, got %d", len(filter.Chains))
	}

	input := filter.Chains["INPUT"]
	if input.Policy != "ACCEPT" {
		t.Errorf("expected INPUT policy ACCEPT, got '%s'", input.Policy)
	}

	if len(input.Rules) != 6 {
		t.Fatalf("expected 6 rules in INPUT, got %d", len(input.Rules))
	}

	tests := []struct {
		index int
		name  string
		rule  Rule
	}{
		{0, "lo accept", Rule{Chain: "INPUT", Target: "ACCEPT", InInterface: "lo"}},
		{1, "stateful", Rule{Chain: "INPUT", Target: "ACCEPT", State: "RELATED,ESTABLISHED"}},
		{2, "ssh", Rule{Chain: "INPUT", Target: "ACCEPT", Protocol: "tcp", DstPort: "22"}},
		{3, "http drop", Rule{Chain: "INPUT", Target: "DROP", Protocol: "tcp", DstPort: "80"}},
		{4, "src block", Rule{Chain: "INPUT", Target: "DROP", Source: "10.0.0.0/8"}},
		{5, "default drop", Rule{Chain: "INPUT", Target: "DROP"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := input.Rules[tt.index]
			if got.Chain != tt.rule.Chain {
				t.Errorf("chain: got '%s', want '%s'", got.Chain, tt.rule.Chain)
			}
			if got.Target != tt.rule.Target {
				t.Errorf("target: got '%s', want '%s'", got.Target, tt.rule.Target)
			}
			if got.Protocol != tt.rule.Protocol {
				t.Errorf("protocol: got '%s', want '%s'", got.Protocol, tt.rule.Protocol)
			}
			if got.Source != tt.rule.Source {
				t.Errorf("source: got '%s', want '%s'", got.Source, tt.rule.Source)
			}
			if got.DstPort != tt.rule.DstPort {
				t.Errorf("dst_port: got '%s', want '%s'", got.DstPort, tt.rule.DstPort)
			}
			if got.InInterface != tt.rule.InInterface {
				t.Errorf("in_interface: got '%s', want '%s'", got.InInterface, tt.rule.InInterface)
			}
			if got.State != tt.rule.State {
				t.Errorf("state: got '%s', want '%s'", got.State, tt.rule.State)
			}
		})
	}

	forward := filter.Chains["FORWARD"]
	if forward.Policy != "DROP" {
		t.Errorf("expected FORWARD policy DROP, got '%s'", forward.Policy)
	}
	if len(forward.Rules) != 0 {
		t.Errorf("expected 0 rules in FORWARD, got %d", len(forward.Rules))
	}

	output := filter.Chains["OUTPUT"]
	if output.Policy != "ACCEPT" {
		t.Errorf("expected OUTPUT policy ACCEPT, got '%s'", output.Policy)
	}
}

func TestParseRule(t *testing.T) {
	tests := []struct {
		line string
		want Rule
	}{
		{
			line: "-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT",
			want: Rule{Chain: "INPUT", Target: "ACCEPT", Protocol: "tcp", DstPort: "443"},
		},
		{
			line: "-A INPUT -s 192.168.1.0/24 -p udp --sport 53 -j ACCEPT",
			want: Rule{Chain: "INPUT", Target: "ACCEPT", Source: "192.168.1.0/24", Protocol: "udp", SrcPort: "53"},
		},
		{
			line: "-A FORWARD -i eth0 -o eth1 -j DROP",
			want: Rule{Chain: "FORWARD", Target: "DROP", InInterface: "eth0", OutInterface: "eth1"},
		},
		{
			line: "-A INPUT -m state --state NEW -j ACCEPT",
			want: Rule{Chain: "INPUT", Target: "ACCEPT", State: "NEW"},
		},
		{
			line: `-A INPUT -j LOG --log-prefix "FW DENY: "`,
			want: Rule{Chain: "INPUT", Target: "LOG", LogPrefix: "FW DENY: "},
		},
	}

	for _, tt := range tests {
		t.Run(tt.line, func(t *testing.T) {
			got := parseRule(tt.line)
			if got.Chain != tt.want.Chain {
				t.Errorf("Chain: got '%s', want '%s'", got.Chain, tt.want.Chain)
			}
			if got.Target != tt.want.Target {
				t.Errorf("Target: got '%s', want '%s'", got.Target, tt.want.Target)
			}
			if got.Protocol != tt.want.Protocol {
				t.Errorf("Protocol: got '%s', want '%s'", got.Protocol, tt.want.Protocol)
			}
			if got.Source != tt.want.Source {
				t.Errorf("Source: got '%s', want '%s'", got.Source, tt.want.Source)
			}
			if got.SrcPort != tt.want.SrcPort {
				t.Errorf("SrcPort: got '%s', want '%s'", got.SrcPort, tt.want.SrcPort)
			}
			if got.DstPort != tt.want.DstPort {
				t.Errorf("DstPort: got '%s', want '%s'", got.DstPort, tt.want.DstPort)
			}
			if got.InInterface != tt.want.InInterface {
				t.Errorf("InInterface: got '%s', want '%s'", got.InInterface, tt.want.InInterface)
			}
			if got.OutInterface != tt.want.OutInterface {
				t.Errorf("OutInterface: got '%s', want '%s'", got.OutInterface, tt.want.OutInterface)
			}
			if got.State != tt.want.State {
				t.Errorf("State: got '%s', want '%s'", got.State, tt.want.State)
			}
			if got.LogPrefix != tt.want.LogPrefix {
				t.Errorf("LogPrefix: got '%s', want '%s'", got.LogPrefix, tt.want.LogPrefix)
			}
		})
	}
}
